### ISSUE TITLE
automated release builds with github actions

### ISSUE THREAD

**Issue by ScanMountGoat** [RoccoDev/bdat-rs#6]
This will make it easier for people that don't want to compile the program from source. It looks like it should just be a matter of copying some of ci.yml to a new file with a trigger for releases.

**Comment by RoccoDev** [comment]
Usually I'd rely on my existing setup to publish artifacts on each commit, though I've noticed they get deleted after 90 days.

I think I'll create releases for each tag and have the runner build artifacts for them, like you suggested. This will also give me the opportunity to explain what changed on each release and if any steps are required for migration.

I'll work on this in the coming days. Thanks!

**Comment by RoccoDev** [comment]
I've added a script. In case you need it, it's https://github.com/RoccoDev/bdat-rs/blob/master/.github/workflows/release.yml

The script builds the executables on release and adds them to the new release as artifacts. It also supports manually rebuilding a release's artifacts with the `workflow_dispatch` option.

I've then created releases for the 0.2.0, 0.3.0, and 0.4.0 tags, and triggered builds for all of them. They should now be available [here](https://github.com/RoccoDev/bdat-rs/releases).
