### ISSUE TITLE
--hashes <HASHES>

### ISSUE THREAD

**Issue by wandersonareis** [RoccoDev/bdat-rs#7]
What would be the file format for hashes? I tried a CSV with hashes, and it didn't work. I also didn't see any examples in the code.

[XC3 Hashes](https://xenobladedata.github.io/xb3_hashes.csv)

**Comment by RoccoDev** [comment]
Hi, you just need the plain names. From that CSV file, you can just copy the second column and put one entry per line, i.e.

```
gimmickAffordance
gimmickEnemyAff
...
```

**Comment by wandersonareis** [comment]
I used this and it didn't work. Some keys and values ​​remained as hashes.
[example.zip](https://github.com/RoccoDev/bdat-rs/files/14337700/example.zip)

**Comment by RoccoDev** [comment]
Unfortunately it doesn't seem like those four tables have known names for their hashes. I think the CSV you sent is kept in sync with this [index](https://xenobladedata.github.io/xb3_200_dlc4/), the unnamed hashes you see here don't have a known name.

**Comment by wandersonareis** [comment]
Perhaps the fields cannot be converted. In this file, Label is still in hash format, and Name is the corresponding text.
To prepare the files for localization, I need to have a standard for the files. Being in hash format is better than a mix of hash and non-hash.

Thank you for your time.
[no label name](https://xenobladedata.github.io/xb3_200_dlc4/msg_mnu_action_hud.html)

**Comment by RoccoDev** [comment]
That's right, the tool currently only converts hashes for column and table names. Hashed fields are IDs and are mostly uncharted territory, though we do have a version of the game (1.3.0) which had some plain names left over. ([example](https://xenobladedata.github.io/xb3_130/CHR_PC.html))

If you only care about changing the string values for localization, I suppose it's fair to leave everything hashed, conversion in both directions will still work.

**Comment by wandersonareis** [comment]
Leaving XC3 with Label and Name helps to standardize with other games. This way I only need one struct in Go. It avoids a conditional just to handle hashed names.
